# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"Y\n\x08Location\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t\"!\n\nLocationId\x12\x13\n\x0blocation_id\x18\x01 \x01(\t\"m\n\x10LocationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t2l\n\x0fLocationService\x12/\n\x0bGetLocation\x12\x0b.LocationId\x1a\x11.LocationResponse\"\x00\x12(\n\x0e\x43reateLocation\x12\t.Location\x1a\t.Location\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOCATION']._serialized_start=18
  _globals['_LOCATION']._serialized_end=107
  _globals['_LOCATIONID']._serialized_start=109
  _globals['_LOCATIONID']._serialized_end=142
  _globals['_LOCATIONRESPONSE']._serialized_start=144
  _globals['_LOCATIONRESPONSE']._serialized_end=253
  _globals['_LOCATIONSERVICE']._serialized_start=255
  _globals['_LOCATIONSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
